#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

if which firefox 1>/dev/null 2>&1; then
  export BROWSER="$(which firefox)"
elif which chromium 1>/dev/null 2>&1; then
  export BROWSER="$(which chromium)"
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.utf8'
fi
export LC_CTYPE="$LANG"

#
# Identity
#
export NAME="Kristoffer Gronlund"
export EMAIL="krig@koru.se"

# Work around for bug in obs-service-tar_scm
export VC_MAILADDR="kgronlund@suse.com"

if [ -f $HOME/Dropbox/my-ip.txt ]; then
  export VAGRANT_HOST="$(cat $HOME/Dropbox/my-ip.txt)"
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

export GOPATH=$HOME/go

# Set the list of directories that Zsh searches for programs.
path=(
  /home/krig/bin
  /home/krig/go/bin
  /home/krig/.cargo/bin
  /usr/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-g -i -M -R -S -w -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

if [ -x /usr/lib/ssh/ksshaskpass ]; then
  export SSH_ASKPASS=/usr/lib/ssh/ksshaskpass
fi

